classifier: {n_estimators: 50, name: rf, seed: 0}
dataset: adult
experiment:
  ckpt: BenchmarkTestHashPassingExample2.pkl
  ckpt_dir: /home/alex/git/work_experiments/BenchmarkTest
  data:
    preprocess: true
    preprocess_opts: null
    split_opts: {method: shuffle, n_train_records: 30000, seed: 0}
  instance_idx: 24
  instance_split: test
  n_runs: 100
  profile: true
  profile_dir: /home/alex/git/work_experiments/ProfileData
  profile_out: benchmark_stats.cprof
  save:
    fields: [feat_ids, feat_names, precision, coverage, covered_true, covered_false]
    mapping:
      covered_false: [raw, examples, covered_false]
      covered_true: [raw, examples, covered_true]
      feat_ids: [raw, feature]
      feat_names: [raw, names]
  show_covered: false
  test_only: false
  verbose: true
explainer:
  beam_size: 0
  disc_perc: !!python/tuple [25, 50, 75]
  parallel: false
  seed: 0
  threshold: 0.95
  type: tabular
  verbose: false
